# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='admin_name',
            field=models.CharField(default=None, max_length=50, verbose_name='操作员名字'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='rejected_note',
            field=models.CharField(default=None, max_length=200, verbose_name='工单备注'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_note',
            field=models.CharField(default=None, max_length=200, verbose_name='工单备注'),
        ),
    ]
