# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190305_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='work_status',
            field=models.SmallIntegerField(default=0, verbose_name='工单状态; -2：代表管理员驳回，-1：代表审核员驳回，0：代表审核员审核中, 1：代表管理操作中，2：工单完成'),
        ),
    ]
