# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190305_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='admin_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='auditor',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='author',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='db_name',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='db_port',
            field=models.PositiveIntegerField(default=3306, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='db_sql',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='instance',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='rejected_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_id',
            field=models.PositiveIntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_status',
            field=models.SmallIntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='workname',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
