# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190305_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='admin_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='auditor',
            field=models.CharField(max_length=50, verbose_name='工单设计人'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='author',
            field=models.CharField(max_length=50, verbose_name='工单所有者'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_id',
            field=models.PositiveIntegerField(default=0, verbose_name='工单ID'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_status',
            field=models.SmallIntegerField(default=0, verbose_name='工单状态 -2 代表管理员驳回 -1 代表审核员驳回 0 代表审核员审核中 1 代表管理员操作中 2 代表工单完成'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='workname',
            field=models.CharField(max_length=200, verbose_name='工单名称'),
        ),
    ]
