# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190305_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='created_time',
            new_name='c_time',
        ),
        migrations.RenameField(
            model_name='worksheet',
            old_name='admin_name',
            new_name='dba',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='updated_time',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='u_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
