# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190305_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSheet_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.PositiveIntegerField(default=0, verbose_name='工单ID')),
                ('workname', models.CharField(max_length=200, verbose_name='工单名称')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.CharField(max_length=50, verbose_name='工单所有者')),
                ('auditor', models.CharField(max_length=50, verbose_name='工单设计人')),
                ('dba', models.CharField(blank=True, default='', max_length=50, verbose_name='管理员')),
                ('work_status', models.SmallIntegerField(default=0, verbose_name='工单状态 -2 代表管理员驳回 -1 代表审核员驳回 0 代表审核员审核中 1 代表管理员操作中 2 代表工单完成')),
                ('instance', models.CharField(max_length=200, verbose_name='')),
                ('db_name', models.CharField(max_length=50, verbose_name='')),
                ('db_port', models.PositiveIntegerField(default=3306, verbose_name='')),
                ('db_sql', models.CharField(max_length=200, verbose_name='')),
                ('work_note', models.CharField(blank=True, default='', max_length=500, verbose_name='')),
                ('rejected_note', models.CharField(blank=True, default='', max_length=500, verbose_name='')),
            ],
            options={
                'ordering': 'updated_time',
            },
        ),
    ]
