# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_worksheet_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet_test',
            name='work_status',
        ),
    ]
