# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_worksheet_test_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet_test',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='c_time',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='db_name',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='db_port',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='db_sql',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='dba',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='rejected_note',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='u_time',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='work_note',
        ),
        migrations.RemoveField(
            model_name='worksheet_test',
            name='workname',
        ),
    ]
