# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190305_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet_test',
            options={'ordering': ('workname',)},
        ),
    ]
