# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190307_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ('u_time', 'c_time')},
        ),
    ]
