# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190308_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='auditor',
            field=models.CharField(blank=True, max_length=50, verbose_name='工单设计人'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='工单所有者'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='db_name',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='instance',
            field=models.CharField(blank=True, max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='workname',
            field=models.CharField(blank=True, max_length=200, verbose_name='工单名称'),
        ),
    ]
