# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190308_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='rejected_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
    ]
