# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190313_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='db_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='数据库名'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='db_port',
            field=models.PositiveIntegerField(default=3306, verbose_name='实例端口'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='db_sql',
            field=models.TextField(default='', verbose_name='执行语句'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='instance',
            field=models.CharField(blank=True, max_length=200, verbose_name='实例名'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_note',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='工单备注'),
        ),
    ]
