# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190313_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ('c_time',)},
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='work_status',
            field=models.SmallIntegerField(default=0, verbose_name='工单状态 -2 管理员驳回 -1 审核员驳回 0 审核中 1 等待管理员操作 2 等待程序处理 3 代表工单完成'),
        ),
    ]
