# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190318_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='InceptionRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.PositiveIntegerField(verbose_name='工单ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.CharField(max_length=50, verbose_name='工单所有者')),
                ('dba', models.CharField(max_length=50, verbose_name='管理员')),
                ('instance', models.CharField(max_length=200, verbose_name='实例名')),
                ('db_sql', models.TextField(verbose_name='执行语句')),
                ('exec_way', models.SmallIntegerField(verbose_name='执行方式 0 为默认值 1 代表自动执行 2代表手动执行')),
                ('exec_timepoint', models.SmallIntegerField(verbose_name='执行的时间点 0 为默认值 1 立即执行 2 第二天凌晨2点执行')),
                ('exec_status', models.SmallIntegerField(verbose_name='执行的状态值 1 执行成功 -1执行失败')),
                ('stage', models.CharField(max_length=50, verbose_name='stage')),
                ('errlevel', models.PositiveIntegerField(verbose_name='errlevel')),
                ('stagestatus', models.CharField(max_length=200, verbose_name='stagestatus')),
                ('errormessage', models.TextField(verbose_name='errormessage')),
                ('SQL', models.TextField(verbose_name='SQL')),
                ('Affected_rows', models.PositiveIntegerField(verbose_name='Affected_rows')),
                ('sequence', models.CharField(max_length=200, verbose_name='sequence')),
                ('backup_dbname', models.CharField(max_length=500, verbose_name='backup_dbname')),
                ('execute_time', models.CharField(max_length=50, verbose_name='execute_time')),
                ('sqlsha1', models.CharField(max_length=200, verbose_name='sequence')),
            ],
            options={
                'ordering': ('c_time',),
            },
        ),
    ]
