# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_inceptionres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inceptionres',
            name='author',
        ),
        migrations.RemoveField(
            model_name='inceptionres',
            name='db_sql',
        ),
        migrations.RemoveField(
            model_name='inceptionres',
            name='dba',
        ),
        migrations.RemoveField(
            model_name='inceptionres',
            name='exec_timepoint',
        ),
        migrations.RemoveField(
            model_name='inceptionres',
            name='exec_way',
        ),
        migrations.RemoveField(
            model_name='inceptionres',
            name='instance',
        ),
    ]
