# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190319_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='exec_datetime',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='exec_status',
        ),
        migrations.AlterField(
            model_name='inceptionres',
            name='errormessage',
            field=models.CharField(max_length=1000, verbose_name='errormessage'),
        ),
    ]
