# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190319_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionres',
            name='Affected_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Affected_rows'),
        ),
        migrations.AlterField(
            model_name='inceptionres',
            name='backup_dbname',
            field=models.CharField(default='', max_length=500, verbose_name='backup_dbname'),
        ),
        migrations.AlterField(
            model_name='inceptionres',
            name='execute_time',
            field=models.CharField(default='', max_length=50, verbose_name='execute_time'),
        ),
        migrations.AlterField(
            model_name='inceptionres',
            name='sequence',
            field=models.CharField(default='', max_length=200, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='inceptionres',
            name='sqlsha1',
            field=models.CharField(default='', max_length=200, verbose_name='sequence'),
        ),
        migrations.AlterField(
            model_name='inceptionres',
            name='stage',
            field=models.CharField(default='', max_length=50, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='inceptionres',
            name='stagestatus',
            field=models.CharField(default='', max_length=200, verbose_name='stagestatus'),
        ),
    ]
