# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190319_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionres',
            name='Affected_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Affected_rows'),
        ),
    ]
