# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190322_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inceptionres',
            name='execute_time',
        ),
    ]
