# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_inceptionres_execute_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionres',
            name='execute_time',
            field=models.CharField(default='', max_length=50, verbose_name='execute_time'),
        ),
    ]
