# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_inceptionres_execute_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionres',
            name='errormessage',
            field=models.TextField(default='', verbose_name='errormessage'),
        ),
    ]
