# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190408_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbtableinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='dbtableinfo',
            name='db_name',
            field=models.CharField(max_length=300, verbose_name='数据库名字'),
        ),
        migrations.AlterField(
            model_name='dbtableinfo',
            name='table_name',
            field=models.CharField(max_length=300, verbose_name='表名字'),
        ),
    ]
