# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20190412_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inceptionres',
            options={'ordering': ('-c_time',)},
        ),
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ('-c_time',)},
        ),
    ]
