# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20190423_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ('c_time',)},
        ),
    ]
