# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190423_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inceptionres',
            options={'ordering': ('c_time',)},
        ),
    ]
