# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20190423_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbtableinfo',
            name='table_size',
            field=models.FloatField(default=0, max_length=10, verbose_name='表数据空间大小'),
        ),
    ]
